// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Motivation.Data;

#nullable disable

namespace motivation.Migrations
{
    [DbContext(typeof(MotivateDbContext))]
    [Migration("20250115215746_migrations")]
    partial class migrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Motivation.Model.Emotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("emotionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("emotions");
                });

            modelBuilder.Entity("Motivation.Model.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("emotionIdId")
                        .HasColumnType("int");

                    b.Property<string>("motivation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("quoteCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("emotionIdId");

                    b.ToTable("quotes");
                });

            modelBuilder.Entity("Motivation.Model.Quote", b =>
                {
                    b.HasOne("Motivation.Model.Emotion", "emotionId")
                        .WithMany()
                        .HasForeignKey("emotionIdId");

                    b.Navigation("emotionId");
                });
#pragma warning restore 612, 618
        }
    }
}
