namespace Motivation.Model
{
    public class AIFeedback{
        public int interactionId {get; set;}
        public string SearchWord {get; set;} // this would be the name of the emotion enter/provided by the user
        public string GeneratedQuote {get; set;} // the response generated by the ai
        public DateTime CreatedTime{get; set;}
    }
}